sudo: false
addons:
  apt:
    packages:
      - bison
      - git
      - gperf
services:
  - mongodb
language: c
compiler:
  - gcc
  - clang
install:
  - cd mongo-c-driver && git submodule update && ./autogen.sh --prefix=$HOME/mongo-c-driver && make && make install
cache:
  directories:
    - $HOME/mongo-c-driver
before_script:
  - "mongo test --eval 'db.test.insert({status: \"ok\"})'"
  - cd mruby
  - cp -fp ../.travis_build_config.rb build_config.rb
script:
  - rake all test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/734ad0b2c08673bdcf94
    on_success: always
    on_failure: always
    on_start: never
