sudo: false
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
      - libmongo-client-dev
services:
  - mongodb
language: c
compiler:
  - gcc
  - clang
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-mongo/.travis_build_config.rb build_config.rb
  - "mongo test --eval 'db.test.insert({status: \"ok\"})'"
script:
  - rake all test
